export const INITIAL_LOAD = 'INITIAL_LOAD'

export const SET_FORM_FOCUS = 'SET_FORM_FOCUS'
export const SET_FORM_VALUES = 'SET_FORM_VALUES'

export const SHOW_MESSAGE = 'SHOW_MESSAGE'
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'
export const RESET_MESSAGES = 'RESET_MESSAGES'

export const FETCH_REPO = 'FETCH_REPO'
