export const NAME_TYPE = 'name'
export const EMAIL_TYPE = 'email_address'
export const OPENING_TIMESTAMP_TYPE = 'opening_timestamp'
export const CLOSING_TIMESTAMP_TYPE = 'closing_timestamp'
export const EMPLOYEE_TYPE = 'employee_name'
export const OPEN_STATUS_TYPE = 'open_status'
export const LOCATION_TYPE = 'location'
